[package]
name = "adm-mqtt-client"
version = "0.1.0"
authors = ["Alex Hamilton <alex.hamilton@ou.edu>"]
edition = "2018"

[dependencies]
adm = { version = "0.1.0", path = "../adm" }
rumqtt = { git = "https://github.com/AtherEnergy/rumqtt" }
serde_json = "1.0.34"
